In [2]:
import concurrent.futures
import dataclasses
import io

import fsspec
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
def read_speedhive_csv(url: str) -> pd.DataFrame:
    with fsspec.open(url) as f:
        data = f.read()
        data = data.replace(b'",', b" ")
    return pd.read_csv(io.BytesIO(data))


def parse_laptime_seconds(s: pd.Series) -> pd.Series:
    """Parse '1:26.354' / '58.201' style strings to seconds (float)."""
    parts = s.str.rsplit(":", n=3, expand=True)
    isna = parts[1].isna()
    parts[1] = parts[1].where(~isna, parts[0])
    parts[0] = parts[0].where(~isna, 0)
    return pd.to_timedelta(
        parts[0].astype(float) * 60 + parts[1].astype(float), unit="s"
    )


@dataclasses.dataclass
class SpeedhiveSession:
    session_id: int
    name: str

    def base_url(self) -> str:
        return f"https://eventresults-api.speedhive.com/api/v0.2.3/eventresults/sessions/{self.session_id}"

    def results_df(self) -> pd.DataFrame:
        return (
            read_speedhive_csv(f"{self.base_url()}/csv")
            .set_index("Pos")
            .rename_axis(index=None)
        )

    def competitor_data(self, pos: int) -> pd.DataFrame:
        with fsspec.open(f"{self.base_url()}/lapdata/{pos}/csv", "rb") as f:
            data = f.read()

        df = pd.read_csv(io.BytesIO(data.replace(b'",', b" ")), header=0)
        df.iloc[16:20]

        df = df.assign(lap_time=lambda d: d["Lap Time"].pipe(parse_laptime_seconds))
        return df

    def laptimes(self) -> pd.DataFrame:
        results_df = self.results_df()
        with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
            return pd.DataFrame(
                dict(
                    executor.map(
                        lambda i_row: (
                            i_row[1]["Competitor"],
                            self.competitor_data(i_row[0])["lap_time"],
                        ),
                        results_df.iterrows(),
                    )
                )
            )


mk_6hr = SpeedhiveSession(session_id=11880076, name="2026-jul-sp-3h")
laptimes = mk_6hr.laptimes()
mk_6hr.results_df()

,Start Number,Competitor,Class,Total Time,Diff,Laps,Best Lap,Best Lap No.,Best Speed
1,118,Clean Bulls Racing,2026 Endurance 2 Stroke,6:0:46.399,0.000,297,1:6.608,11,73.505 km/h
2,111,James King,2026 Endurance 2 Stroke,6:0:52.018,5.619,297,1:6.700,17,73.403 km/h
3,116,Triple Threat,2026 Endurance 2 Stroke,6:1:11.654,1 lap,296,1:7.167,9,72.893 km/h
4,105,ASH.KING,2026 Endurance 2 Stroke,6:1:37.911,3 laps,294,1:7.397,6,72.644 km/h
5,123,Phoenix DMAX,2026 Endurance 2 Stroke,6:1:38.379,5 laps,292,1:7.035,75,73.036 km/h
6,104,Apex Nova Racing,2026 Endurance 2 Stroke,6:1:51.629,6 laps,291,1:7.289,6,72.761 km/h
7,121,GKA Racing,2026 Endurance 2 Stroke,6:1:3.611,10 laps,287,1:7.526,32,72.505 km/h
8,113,Nomex Racing,2026 Endurance 2 Stroke,6:1:46.037,11 laps,286,1:7.373,19,72.670 km/h
9,117,The Mandem,2026 Endurance 2 Stroke,6:1:55.169,12 laps,285,1:7.760,204,72.255 km/h
10,106,5 Dollar Head,2026 Endurance 2 Stroke,6:1:51.056,17 laps,280,1:7.519,20,72.513 km/h
11,103,Yellow Sector,2026 Endurance 2 Stroke,6:1:52.703,18 laps,279,1:7.464,4,72.572 km/h
12,110,WPR,2026 Endurance 2 Stroke,6:1:36.265,19 laps,278,1:7.758,12,72.257 km/h
13,114,The Flying Havaianas,2026 Endurance 2 Stroke,6:1:27.435,20 laps,277,1:7.484,16,72.551 km/h
14,112,TRX Academy,2026 Endurance 2 Stroke,6:1:38.066,20 laps,277,1:7.890,97,72.117 km/h
15,102,HHR x RATDOG,2026 Endurance 2 Stroke,6:1:37.758,23 laps,274,1:7.208,31,72.848 km/h
16,122,Vertice Racing DMAX,2026 Endurance 2 Stroke,6:1:9.675,25 laps,272,1:7.837,33,72.173 km/h
17,100,The Burnouts,2026 Endurance 2 Stroke,6:0:48.494,26 laps,271,1:8.377,174,71.603 km/h
18,109,MIND,2026 Endurance 2 Stroke,6:1:9.306,27 laps,270,1:7.690,4,72.330 km/h
19,16,NW Racing,2026 Endurance 4 Stroke,6:1:54.672,28 laps,269,1:15.475,240,64.869 km/h
20,1,Senna's Squadron by DNH,2026 Endurance 4 Stroke,6:1:42.379,29 laps,268,1:15.258,17,65.056 km/h
21,18,Phoenix Sodi,2026 Endurance 4 Stroke,6:1:46.405,29 laps,268,1:14.913,16,65.356 km/h
22,20,DNH Dad's,2026 Endurance 4 Stroke,6:0:52.277,30 laps,267,1:15.631,264,64.735 km/h
23,11,Miles-Shelby Squad by DNH,2026 Endurance 4 Stroke,6:1:8.644,30 laps,267,1:14.784,248,65.469 km/h
24,3,Cole Clarke Racing,2026 Endurance 4 Stroke,6:1:56.618,30 laps,267,1:15.739,16,64.643 km/h
25,6,Misfits,2026 Endurance 4 Stroke,6:1:26.270,31 laps,266,1:15.560,175,64.796 km/h
26,29,Mere Racing,2026 Endurance 4 Stroke,6:1:50.049,32 laps,265,1:15.704,253,64.673 km/h
27,25,Noot Noot,2026 Endurance 4 Stroke,6:1:57.978,32 laps,265,1:14.944,232,65.329 km/h
28,4,DNH Boldero,2026 Endurance 4 Stroke,6:2:1.351,33 laps,264,1:15.828,261,64.567 km/h
29,23,Vertice Racing Sodi,2026 Endurance 4 Stroke,6:0:59.218,35 laps,262,1:15.847,72,64.551 km/h
30,9,SDR,2026 Endurance 4 Stroke,6:1:13.952,35 laps,262,1:15.755,22,64.629 km/h
31,108,NMX Racing,2026 Endurance 2 Stroke,6:1:18.515,35 laps,262,1:11.074,4,68.886 km/h
32,5,Three Bears Motorsport,2026 Endurance 4 Stroke,6:0:53.255,36 laps,261,1:15.801,251,64.590 km/h
33,7,TRX Motorsport,2026 Endurance 4 Stroke,6:2:1.388,36 laps,261,1:15.125,228,65.171 km/h
34,24,Hawthorn's Heroes by DNH,2026 Endurance 4 Stroke,6:0:58.371,38 laps,259,1:15.754,204,64.630 km/h
35,17,Midfield Masters,2026 Endurance 4 Stroke,6:1:42.035,38 laps,259,1:15.589,89,64.771 km/h
36,28,Rocket Racing Club,2026 Endurance 4 Stroke,6:1:42.408,38 laps,259,1:16.392,251,64.090 km/h
37,13,Iron Dames by DNH,2026 Endurance 4 Stroke,6:1:30.747,40 laps,257,1:15.747,225,64.636 km/h
38,12,Clear Horizon Racing,2026 Endurance 4 Stroke,6:1:47.266,42 laps,255,1:17.132,235,63.476 km/h
39,14,MSKT,2026 Endurance 4 Stroke,6:1:24.694,45 laps,252,1:16.106,130,64.331 km/h
40,15,Watkins Glen by DNH,2026 Endurance 4 Stroke,6:1:49.663,46 laps,251,1:16.201,220,64.251 km/h
41,2,Wanganator Motorsport,2026 Endurance 4 Stroke,6:1:25.930,54 laps,243,1:17.615,38,63.081 km/h
42,19,5 Dollar Helmet,2026 Endurance 4 Stroke,6:1:8.140,55 laps,242,1:17.510,240,63.166 km/h

In [41]:
def plot_gap_to_mean_leader(laptimes: pd.DataFrame) -> go.Figure:
    leader_mean_lap = laptimes.iloc[:, 0].mean()
    return px.line(
        laptimes.assign(
            **{
                col: lambda d, col=col: (
                    (leader_mean_lap - d[col]).cumsum().dt.total_seconds()
                )
                for col in laptimes.columns
            }
        ),
        title="Gap to leader mean lap time (cumulative) - 2026 Apr Dayona MK 6h",
    )


plot_gap_to_mean_leader(laptimes)

In [25]:
king = mk_6hr.competitor_data(2)
triple = mk_6hr.competitor_data(3)

In [33]:
king

,Lap,Pos,Lap Time,Diff to Last Lap,Diff to Best Lap,Gap in Front,Diff to P1,Speed,lap_time
0,1,3,1:10.929,0.000,4.229,0.274,1.041,69.027 km/h,0 days 00:01:10.929000
1,2,3,1:8.117,-,1.417,0.319,1.271,71.876 km/h,0 days 00:01:08.117000
2,3,3,1:11.418,3.301,4.718,0.328,1.404,68.554 km/h,0 days 00:01:11.418000
3,4,3,1:7.175,-,0.475,0.326,1.857,72.884 km/h,0 days 00:01:07.175000
4,5,3,1:7.953,0.778,1.253,0.949,2.598,72.050 km/h,0 days 00:01:07.953000
...,...,...,...,...,...,...,...,...,...
290,291,2,1:9.071,0.084,2.371,1 lap,1 lap,70.884 km/h,0 days 00:01:09.071000
291,292,2,1:8.743,-,2.043,1 lap,1 lap,71.222 km/h,0 days 00:01:08.743000
292,293,2,1:8.216,-,1.516,1 lap,1 lap,71.772 km/h,0 days 00:01:08.216000
293,294,2,1:7.888,-,1.188,1 lap,1 lap,72.119 km/h,0 days 00:01:07.888000
294,295,2,1:8.817,0.929,2.117,1 lap,1 lap,71.145 km/h,0 days 00:01:08.817000

In [40]:
px.line(
    triple["Gap in Front"]
    .where(lambda s: ~s.str.contains(" "))
    .pipe(parse_laptime_seconds)
    .dt.total_seconds(),
    line_shape="hv",
)

In [39]:
def plot_laptime_distribution(laptimes: pd.DataFrame, limit: int | None) -> go.Figure:
    best_lap = laptimes.where(lambda d: d > d.median().min() * 0.93).min().min()
    return (
        laptimes.where(lambda d: (d > best_lap * 0.93) & (d < best_lap * 1.07))
        .assign(
            **{
                col: lambda d, c=col: d[c].dt.total_seconds()
                for col in laptimes.columns
            }
        )[laptimes.columns[:limit]]
        .pipe(px.violin)
    )


plot_laptime_distribution(laptimes, 3)