In [1]:
# ruff: noqa: F401, F403

import os
import subprocess
import sys

from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import torch

from IPython.display import *

from pacer import (
    CoordinateSystem,
    # read_dat_file,
    DatVersion,
    GPMFSource,
    GPSSample,
    Lap,
    Laps,
    Point,
    PointInTime_GPSSample,
    RawGPSSource,
    Segment,
    SequentialGPSSource,
    Vec3f,
)

In [6]:
file_paths = [
    "/Volumes/Untitled/DCIM/100GOPRO/GX010111.MP4",
]
single_files = [GPMFSource(f) for f in file_paths]

samples = []
start_of_file = {}
end_of_file = {}


for fn, f in zip(file_paths, single_files):
    total_duration = f.get_total_duration()

    def on_sample(s, _, _2):
        if fn not in start_of_file:
            start_of_file[fn] = pd.Timestamp(s.timestamp_ms, unit="ms")
        end_of_file[fn] = pd.Timestamp(s.timestamp_ms, unit="ms")
        if s.full_speed > 3:
            samples.append(s)

    while not f.is_end():
        f.read_samples(on_sample)
        f.next()

In [ ]:
import re
import xml.etree.ElementTree as ET


tcx_path = "/Users/denys/Downloads/2025-11-08-frol-mk-dmax-frol.tcx"

samples = []


with open(tcx_path, "r") as xml_file:
    xml_str = xml_file.read()
    xml_str = re.sub(' xmlns="[^"]+"', "", xml_str, count=1)
    root = ET.fromstring(xml_str)
    activities = root.findall(".//Activity")
    for activity in activities:
        print("-- {} --".format(activity.attrib["Sport"]))
        prev_distance = 0.0
        tracking_points = activity.findall(".//Trackpoint")
        for tracking_point in list(tracking_points):
            distance = float(tracking_point.find("./DistanceMeters").text)
            sample = GPSSample(
                altitude=float(tracking_point.find("./AltitudeMeters").text),
                lon=float(tracking_point.find("./Position/LongitudeDegrees").text),
                lat=float(tracking_point.find("./Position/LatitudeDegrees").text),
                full_speed=distance - prev_distance,
                timestamp_ms=pd.to_datetime(tracking_point.find("./Time").text).value
                // 10**6,
            )
            prev_distance = distance

            print(
                {
                    "time": pd.to_datetime(tracking_point.find("./Time").text),
                    "hr": int(tracking_point.find("./HeartRateBpm/Value").text),
                    "sample": sample,
                }
            )
            samples.append(sample)

-- Biking --
{'time': Timestamp('2025-11-08 12:51:29+0000', tz='UTC'), 'hr': 97, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606289000)}
{'time': Timestamp('2025-11-08 12:51:30+0000', tz='UTC'), 'hr': 98, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606290000)}
{'time': Timestamp('2025-11-08 12:51:41+0000', tz='UTC'), 'hr': 101, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606301000)}
{'time': Timestamp('2025-11-08 12:51:45+0000', tz='UTC'), 'hr': 102, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606305000)}
{'time': Timestamp('2025-11-08 12:52:00+0000', tz='UTC'), 'hr': 102, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606320000)}
{'time': Timestamp('2025-11-08 12:52:10+0000', tz='UTC'), 'hr': 105, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606330000)}
{'time': Timestamp('2025-11-08 12:52:13+0000', tz='UTC'), 'hr': 108, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606333000)}
{'time': Timestamp('2025-11-08 12:52:20+0000', tz='UTC'), 'hr': 110, 'sample': GPSSample(lat=52.040365, lon=-0.784948, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606340000)}
{'time': Timestamp('2025-11-08 12:52:36+0000', tz='UTC'), 'hr': 110, 'sample': GPSSample(lat=52.040365, lon=-0.784950, altitude=77.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606356000)}
{'time': Timestamp('2025-11-08 12:52:40+0000', tz='UTC'), 'hr': 109, 'sample': GPSSample(lat=52.040272, lon=-0.785049, altitude=77.599998, full_speed=12.260000, ground_speed=0.000000, timestamp_ms=1762606360000)}
{'time': Timestamp('2025-11-08 12:52:43+0000', tz='UTC'), 'hr': 107, 'sample': GPSSample(lat=52.040153, lon=-0.785077, altitude=77.599998, full_speed=13.270000, ground_speed=0.000000, timestamp_ms=1762606363000)}
{'time': Timestamp('2025-11-08 12:52:44+0000', tz='UTC'), 'hr': 107, 'sample': GPSSample(lat=52.040115, lon=-0.785042, altitude=77.400002, full_speed=5.039999, ground_speed=0.000000, timestamp_ms=1762606364000)}
{'time': Timestamp('2025-11-08 12:52:45+0000', tz='UTC'), 'hr': 106, 'sample': GPSSample(lat=52.040086, lon=-0.784999, altitude=77.400002, full_speed=4.529999, ground_speed=0.000000, timestamp_ms=1762606365000)}
{'time': Timestamp('2025-11-08 12:52:47+0000', tz='UTC'), 'hr': 105, 'sample': GPSSample(lat=52.040009, lon=-0.784869, altitude=77.400002, full_speed=12.500000, ground_speed=0.000000, timestamp_ms=1762606367000)}
{'time': Timestamp('2025-11-08 12:52:48+0000', tz='UTC'), 'hr': 105, 'sample': GPSSample(lat=52.039958, lon=-0.784781, altitude=77.400002, full_speed=8.100002, ground_speed=0.000000, timestamp_ms=1762606368000)}
{'time': Timestamp('2025-11-08 12:52:49+0000', tz='UTC'), 'hr': 104, 'sample': GPSSample(lat=52.039900, lon=-0.784700, altitude=77.199997, full_speed=8.530003, ground_speed=0.000000, timestamp_ms=1762606369000)}
{'time': Timestamp('2025-11-08 12:52:52+0000', tz='UTC'), 'hr': 105, 'sample': GPSSample(lat=52.039669, lon=-0.784367, altitude=77.400002, full_speed=33.669998, ground_speed=0.000000, timestamp_ms=1762606372000)}
{'time': Timestamp('2025-11-08 12:52:54+0000', tz='UTC'), 'hr': 104, 'sample': GPSSample(lat=52.039536, lon=-0.784128, altitude=77.599998, full_speed=21.729996, ground_speed=0.000000, timestamp_ms=1762606374000)}
{'time': Timestamp('2025-11-08 12:52:55+0000', tz='UTC'), 'hr': 104, 'sample': GPSSample(lat=52.039525, lon=-0.784012, altitude=77.800003, full_speed=8.400002, ground_speed=0.000000, timestamp_ms=1762606375000)}
{'time': Timestamp('2025-11-08 12:52:56+0000', tz='UTC'), 'hr': 103, 'sample': GPSSample(lat=52.039548, lon=-0.783924, altitude=78.000000, full_speed=6.089996, ground_speed=0.000000, timestamp_ms=1762606376000)}
{'time': Timestamp('2025-11-08 12:52:57+0000', tz='UTC'), 'hr': 103, 'sample': GPSSample(lat=52.039587, lon=-0.783868, altitude=78.000000, full_speed=5.889999, ground_speed=0.000000, timestamp_ms=1762606377000)}
{'time': Timestamp('2025-11-08 12:52:58+0000', tz='UTC'), 'hr': 103, 'sample': GPSSample(lat=52.039623, lon=-0.783822, altitude=78.000000, full_speed=4.310013, ground_speed=0.000000, timestamp_ms=1762606378000)}
{'time': Timestamp('2025-11-08 12:52:59+0000', tz='UTC'), 'hr': 103, 'sample': GPSSample(lat=52.039644, lon=-0.783738, altitude=78.199997, full_speed=5.629990, ground_speed=0.000000, timestamp_ms=1762606379000)}
{'time': Timestamp('2025-11-08 12:53:00+0000', tz='UTC'), 'hr': 104, 'sample': GPSSample(lat=52.039630, lon=-0.783641, altitude=78.599998, full_speed=6.710007, ground_speed=0.000000, timestamp_ms=1762606380000)}
{'time': Timestamp('2025-11-08 12:53:02+0000', tz='UTC'), 'hr': 104, 'sample': GPSSample(lat=52.039515, lon=-0.783470, altitude=78.599998, full_speed=16.610001, ground_speed=0.000000, timestamp_ms=1762606382000)}
{'time': Timestamp('2025-11-08 12:53:04+0000', tz='UTC'), 'hr': 108, 'sample': GPSSample(lat=52.039374, lon=-0.783273, altitude=78.800003, full_speed=19.860001, ground_speed=0.000000, timestamp_ms=1762606384000)}
{'time': Timestamp('2025-11-08 12:53:05+0000', tz='UTC'), 'hr': 109, 'sample': GPSSample(lat=52.039356, lon=-0.783161, altitude=78.800003, full_speed=7.309998, ground_speed=0.000000, timestamp_ms=1762606385000)}
{'time': Timestamp('2025-11-08 12:53:06+0000', tz='UTC'), 'hr': 108, 'sample': GPSSample(lat=52.039380, lon=-0.783062, altitude=78.800003, full_speed=6.619995, ground_speed=0.000000, timestamp_ms=1762606386000)}
{'time': Timestamp('2025-11-08 12:53:07+0000', tz='UTC'), 'hr': 109, 'sample': GPSSample(lat=52.039431, lon=-0.783033, altitude=78.800003, full_speed=5.440002, ground_speed=0.000000, timestamp_ms=1762606387000)}
{'time': Timestamp('2025-11-08 12:53:08+0000', tz='UTC'), 'hr': 109, 'sample': GPSSample(lat=52.039500, lon=-0.783061, altitude=78.800003, full_speed=7.320007, ground_speed=0.000000, timestamp_ms=1762606388000)}
{'time': Timestamp('2025-11-08 12:53:09+0000', tz='UTC'), 'hr': 110, 'sample': GPSSample(lat=52.039575, lon=-0.783139, altitude=78.800003, full_speed=9.719986, ground_speed=0.000000, timestamp_ms=1762606389000)}
{'time': Timestamp('2025-11-08 12:53:11+0000', tz='UTC'), 'hr': 111, 'sample': GPSSample(lat=52.039720, lon=-0.783417, altitude=79.000000, full_speed=25.010010, ground_speed=0.000000, timestamp_ms=1762606391000)}
{'time': Timestamp('2025-11-08 12:53:13+0000', tz='UTC'), 'hr': 112, 'sample': GPSSample(lat=52.039827, lon=-0.783766, altitude=79.199997, full_speed=26.210007, ground_speed=0.000000, timestamp_ms=1762606393000)}
{'time': Timestamp('2025-11-08 12:53:14+0000', tz='UTC'), 'hr': 112, 'sample': GPSSample(lat=52.039912, lon=-0.783858, altitude=79.000000, full_speed=10.599976, ground_speed=0.000000, timestamp_ms=1762606394000)}
{'time': Timestamp('2025-11-08 12:53:15+0000', tz='UTC'), 'hr': 111, 'sample': GPSSample(lat=52.039989, lon=-0.783828, altitude=78.800003, full_speed=7.780029, ground_speed=0.000000, timestamp_ms=1762606395000)}
{'time': Timestamp('2025-11-08 12:53:16+0000', tz='UTC'), 'hr': 112, 'sample': GPSSample(lat=52.040022, lon=-0.783736, altitude=78.599998, full_speed=6.549988, ground_speed=0.000000, timestamp_ms=1762606396000)}
{'time': Timestamp('2025-11-08 12:53:17+0000', tz='UTC'), 'hr': 112, 'sample': GPSSample(lat=52.040001, lon=-0.783592, altitude=78.599998, full_speed=9.850006, ground_speed=0.000000, timestamp_ms=1762606397000)}
{'time': Timestamp('2025-11-08 12:53:19+0000', tz='UTC'), 'hr': 112, 'sample': GPSSample(lat=52.039864, lon=-0.783319, altitude=79.000000, full_speed=23.679993, ground_speed=0.000000, timestamp_ms=1762606399000)}
{'time': Timestamp('2025-11-08 12:53:21+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.039682, lon=-0.783028, altitude=79.400002, full_speed=28.510010, ground_speed=0.000000, timestamp_ms=1762606401000)}
{'time': Timestamp('2025-11-08 12:53:22+0000', tz='UTC'), 'hr': 116, 'sample': GPSSample(lat=52.039601, lon=-0.782889, altitude=79.599998, full_speed=13.169983, ground_speed=0.000000, timestamp_ms=1762606402000)}
{'time': Timestamp('2025-11-08 12:53:23+0000', tz='UTC'), 'hr': 119, 'sample': GPSSample(lat=52.039523, lon=-0.782768, altitude=79.400002, full_speed=11.910004, ground_speed=0.000000, timestamp_ms=1762606403000)}
{'time': Timestamp('2025-11-08 12:53:24+0000', tz='UTC'), 'hr': 119, 'sample': GPSSample(lat=52.039432, lon=-0.782706, altitude=79.199997, full_speed=10.640015, ground_speed=0.000000, timestamp_ms=1762606404000)}
{'time': Timestamp('2025-11-08 12:53:25+0000', tz='UTC'), 'hr': 121, 'sample': GPSSample(lat=52.039339, lon=-0.782684, altitude=79.000000, full_speed=9.720001, ground_speed=0.000000, timestamp_ms=1762606405000)}
{'time': Timestamp('2025-11-08 12:53:26+0000', tz='UTC'), 'hr': 122, 'sample': GPSSample(lat=52.039252, lon=-0.782738, altitude=78.599998, full_speed=9.769989, ground_speed=0.000000, timestamp_ms=1762606406000)}
{'time': Timestamp('2025-11-08 12:53:27+0000', tz='UTC'), 'hr': 123, 'sample': GPSSample(lat=52.039203, lon=-0.782857, altitude=78.400002, full_speed=9.470001, ground_speed=0.000000, timestamp_ms=1762606407000)}
{'time': Timestamp('2025-11-08 12:53:28+0000', tz='UTC'), 'hr': 122, 'sample': GPSSample(lat=52.039190, lon=-0.783015, altitude=78.199997, full_speed=10.540009, ground_speed=0.000000, timestamp_ms=1762606408000)}
{'time': Timestamp('2025-11-08 12:53:29+0000', tz='UTC'), 'hr': 122, 'sample': GPSSample(lat=52.039221, lon=-0.783185, altitude=78.199997, full_speed=11.799988, ground_speed=0.000000, timestamp_ms=1762606409000)}
{'time': Timestamp('2025-11-08 12:53:30+0000', tz='UTC'), 'hr': 122, 'sample': GPSSample(lat=52.039294, lon=-0.783323, altitude=78.400002, full_speed=11.970001, ground_speed=0.000000, timestamp_ms=1762606410000)}
{'time': Timestamp('2025-11-08 12:53:31+0000', tz='UTC'), 'hr': 124, 'sample': GPSSample(lat=52.039384, lon=-0.783448, altitude=78.599998, full_speed=12.529999, ground_speed=0.000000, timestamp_ms=1762606411000)}
{'time': Timestamp('2025-11-08 12:53:32+0000', tz='UTC'), 'hr': 123, 'sample': GPSSample(lat=52.039423, lon=-0.783599, altitude=78.599998, full_speed=10.529999, ground_speed=0.000000, timestamp_ms=1762606412000)}
{'time': Timestamp('2025-11-08 12:53:33+0000', tz='UTC'), 'hr': 122, 'sample': GPSSample(lat=52.039398, lon=-0.783729, altitude=78.599998, full_speed=8.459991, ground_speed=0.000000, timestamp_ms=1762606413000)}
{'time': Timestamp('2025-11-08 12:53:34+0000', tz='UTC'), 'hr': 121, 'sample': GPSSample(lat=52.039322, lon=-0.783773, altitude=78.599998, full_speed=8.690002, ground_speed=0.000000, timestamp_ms=1762606414000)}
{'time': Timestamp('2025-11-08 12:53:35+0000', tz='UTC'), 'hr': 121, 'sample': GPSSample(lat=52.039255, lon=-0.783758, altitude=78.400002, full_speed=7.419983, ground_speed=0.000000, timestamp_ms=1762606415000)}
{'time': Timestamp('2025-11-08 12:53:36+0000', tz='UTC'), 'hr': 120, 'sample': GPSSample(lat=52.039207, lon=-0.783700, altitude=78.199997, full_speed=6.540039, ground_speed=0.000000, timestamp_ms=1762606416000)}
{'time': Timestamp('2025-11-08 12:53:37+0000', tz='UTC'), 'hr': 120, 'sample': GPSSample(lat=52.039162, lon=-0.783629, altitude=78.000000, full_speed=7.029968, ground_speed=0.000000, timestamp_ms=1762606417000)}
{'time': Timestamp('2025-11-08 12:53:38+0000', tz='UTC'), 'hr': 119, 'sample': GPSSample(lat=52.039122, lon=-0.783554, altitude=78.000000, full_speed=6.920044, ground_speed=0.000000, timestamp_ms=1762606418000)}
{'time': Timestamp('2025-11-08 12:53:39+0000', tz='UTC'), 'hr': 119, 'sample': GPSSample(lat=52.039088, lon=-0.783475, altitude=77.800003, full_speed=6.419983, ground_speed=0.000000, timestamp_ms=1762606419000)}
{'time': Timestamp('2025-11-08 12:53:40+0000', tz='UTC'), 'hr': 119, 'sample': GPSSample(lat=52.039046, lon=-0.783383, altitude=78.000000, full_speed=8.089966, ground_speed=0.000000, timestamp_ms=1762606420000)}
{'time': Timestamp('2025-11-08 12:53:43+0000', tz='UTC'), 'hr': 118, 'sample': GPSSample(lat=52.038941, lon=-0.783152, altitude=77.400002, full_speed=19.619995, ground_speed=0.000000, timestamp_ms=1762606423000)}
{'time': Timestamp('2025-11-08 12:53:49+0000', tz='UTC'), 'hr': 115, 'sample': GPSSample(lat=52.038792, lon=-0.782607, altitude=76.400002, full_speed=41.090027, ground_speed=0.000000, timestamp_ms=1762606429000)}
{'time': Timestamp('2025-11-08 12:53:50+0000', tz='UTC'), 'hr': 115, 'sample': GPSSample(lat=52.038781, lon=-0.782518, altitude=76.199997, full_speed=6.130005, ground_speed=0.000000, timestamp_ms=1762606430000)}
{'time': Timestamp('2025-11-08 12:53:51+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038770, lon=-0.782429, altitude=76.000000, full_speed=6.119995, ground_speed=0.000000, timestamp_ms=1762606431000)}
{'time': Timestamp('2025-11-08 12:53:52+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038765, lon=-0.782344, altitude=76.000000, full_speed=5.900024, ground_speed=0.000000, timestamp_ms=1762606432000)}
{'time': Timestamp('2025-11-08 12:53:53+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038773, lon=-0.782263, altitude=76.000000, full_speed=5.639954, ground_speed=0.000000, timestamp_ms=1762606433000)}
{'time': Timestamp('2025-11-08 12:53:54+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038792, lon=-0.782186, altitude=76.000000, full_speed=6.030029, ground_speed=0.000000, timestamp_ms=1762606434000)}
{'time': Timestamp('2025-11-08 12:53:55+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038813, lon=-0.782113, altitude=76.000000, full_speed=5.320007, ground_speed=0.000000, timestamp_ms=1762606435000)}
{'time': Timestamp('2025-11-08 12:53:56+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038834, lon=-0.782024, altitude=76.000000, full_speed=6.510010, ground_speed=0.000000, timestamp_ms=1762606436000)}
{'time': Timestamp('2025-11-08 12:53:57+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.038848, lon=-0.781919, altitude=76.000000, full_speed=7.079956, ground_speed=0.000000, timestamp_ms=1762606437000)}
{'time': Timestamp('2025-11-08 12:53:58+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.038852, lon=-0.781799, altitude=76.000000, full_speed=7.700012, ground_speed=0.000000, timestamp_ms=1762606438000)}
{'time': Timestamp('2025-11-08 12:53:59+0000', tz='UTC'), 'hr': 112, 'sample': GPSSample(lat=52.038884, lon=-0.781706, altitude=76.000000, full_speed=6.880005, ground_speed=0.000000, timestamp_ms=1762606439000)}
{'time': Timestamp('2025-11-08 12:54:00+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.038946, lon=-0.781675, altitude=76.199997, full_speed=6.539978, ground_speed=0.000000, timestamp_ms=1762606440000)}
{'time': Timestamp('2025-11-08 12:54:01+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.039010, lon=-0.781684, altitude=76.199997, full_speed=6.860046, ground_speed=0.000000, timestamp_ms=1762606441000)}
{'time': Timestamp('2025-11-08 12:54:02+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.039048, lon=-0.781718, altitude=76.400002, full_speed=4.940002, ground_speed=0.000000, timestamp_ms=1762606442000)}
{'time': Timestamp('2025-11-08 12:54:03+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.039063, lon=-0.781739, altitude=76.599998, full_speed=2.429993, ground_speed=0.000000, timestamp_ms=1762606443000)}
{'time': Timestamp('2025-11-08 12:54:04+0000', tz='UTC'), 'hr': 114, 'sample': GPSSample(lat=52.039063, lon=-0.781737, altitude=76.800003, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606444000)}
{'time': Timestamp('2025-11-08 12:54:07+0000', tz='UTC'), 'hr': 117, 'sample': GPSSample(lat=52.039063, lon=-0.781737, altitude=76.800003, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606447000)}
{'time': Timestamp('2025-11-08 12:54:09+0000', tz='UTC'), 'hr': 118, 'sample': GPSSample(lat=52.039063, lon=-0.781737, altitude=76.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606449000)}
{'time': Timestamp('2025-11-08 12:54:12+0000', tz='UTC'), 'hr': 115, 'sample': GPSSample(lat=52.039063, lon=-0.781737, altitude=76.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606452000)}
{'time': Timestamp('2025-11-08 12:54:22+0000', tz='UTC'), 'hr': 113, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=76.800003, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606462000)}
{'time': Timestamp('2025-11-08 12:54:29+0000', tz='UTC'), 'hr': 116, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=76.599998, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606469000)}
{'time': Timestamp('2025-11-08 12:54:37+0000', tz='UTC'), 'hr': 115, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606477000)}
{'time': Timestamp('2025-11-08 12:54:47+0000', tz='UTC'), 'hr': 111, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606487000)}
{'time': Timestamp('2025-11-08 12:54:48+0000', tz='UTC'), 'hr': 107, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606488000)}
{'time': Timestamp('2025-11-08 12:54:49+0000', tz='UTC'), 'hr': 99, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606489000)}
{'time': Timestamp('2025-11-08 12:54:50+0000', tz='UTC'), 'hr': 95, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606490000)}
{'time': Timestamp('2025-11-08 12:54:52+0000', tz='UTC'), 'hr': 92, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606492000)}
{'time': Timestamp('2025-11-08 12:55:00+0000', tz='UTC'), 'hr': 92, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606500000)}
{'time': Timestamp('2025-11-08 12:55:02+0000', tz='UTC'), 'hr': 92, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=76.800003, full_speed=0.010010, ground_speed=0.000000, timestamp_ms=1762606502000)}
{'time': Timestamp('2025-11-08 12:55:05+0000', tz='UTC'), 'hr': 92, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606505000)}
{'time': Timestamp('2025-11-08 12:55:11+0000', tz='UTC'), 'hr': 95, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606511000)}
{'time': Timestamp('2025-11-08 12:55:24+0000', tz='UTC'), 'hr': 94, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606524000)}
{'time': Timestamp('2025-11-08 12:55:27+0000', tz='UTC'), 'hr': 90, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606527000)}
{'time': Timestamp('2025-11-08 12:55:36+0000', tz='UTC'), 'hr': 88, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.209961, ground_speed=0.000000, timestamp_ms=1762606536000)}
{'time': Timestamp('2025-11-08 12:55:54+0000', tz='UTC'), 'hr': 86, 'sample': GPSSample(lat=52.039064, lon=-0.781760, altitude=77.000000, full_speed=0.000000, ground_speed=0.000000, timestamp_ms=1762606554000)}

In [4]:
tracking_point.find("./Position/LatitudeDegrees").text

'52.040394991636276'

In [14]:
cs = CoordinateSystem(samples[0])

laps = Laps()
laps.set_coordinate_system(cs)

start_time = pd.to_datetime(samples[0].timestamp_ms, unit="ms")
for s in samples:
    t = (pd.to_datetime(s.timestamp_ms, unit="ms") - start_time).total_seconds()
    laps.add_point(s, t)


def locate_timestamp(timestamp: pd.Timestamp | float):
    if not isinstance(timestamp, pd.Timestamp):
        timestamp = start_time + pd.to_timedelta(timestamp, unit="s")
    assert isinstance(timestamp, pd.Timestamp)
    for f in file_paths:
        if start_of_file[f] <= timestamp < end_of_file[f]:
            return f, timestamp - start_of_file[f]


fig = px.line(x=[cs.local(s).x for s in samples], y=[cs.local(s).y for s in samples])
fig.add_trace(
    px.line(
        x=[laps.sectors.start_line.first.x, laps.sectors.start_line.second.x],
        y=[laps.sectors.start_line.first.y, laps.sectors.start_line.second.y],
    ).data[0]
)

# Play around to set right start line.
s1, s2 = Point(x=-15, y=55), Point(x=0, y=30)
# s3, s4 = Point(x=100, y=-80), Point(x=105, y=-65)
# s5, s6 = Point(x=191, y=-160), Point(x=197, y=-190)

fig.add_trace(px.line(x=[s1.x, s2.x], y=[s1.y, s2.y]).data[0])
# fig.add_trace(px.line(x=[s3.x, s4.x], y=[s3.y, s4.y]).data[0])
# fig.add_trace(px.line(x=[s5.x, s6.x], y=[s5.y, s6.y]).data[0])
fig.update_layout(height=800)

In [8]:
type(laps.sectors.sector_lines)

list

In [15]:
laps.sectors.start_line = Segment(s1, s2)
laps.sectors.sector_lines = [
    # Segment(s3, s4),
    # Segment(s5, s6),
]
laps.update()

laps_times = pd.DataFrame(
    [
        dict(
            lap=i,
            lap_time=laps.lap_time(i),
            **{f"S{j + 1}": laps.sector_time(3 * i + j) for j in range(3)},
        )
        for i in range(laps.laps_count())
    ]
)

# Filter out laps around pits
non_outliars = laps_times["lap_time"] > 10

# Filter out slow laps: in-between sessions, bunch of yellows, etc.
non_outliars &= (
    laps_times["lap_time"] < 1.25 * laps_times.loc[non_outliars, "lap_time"].min()
)

px.line(
    laps_times.where(non_outliars),
    x="lap",
    y="lap_time",
    title=r"Lap times (whitin 125% of the best)",
    markers=True,
)

In [57]:
lap10 = laps.get_lap(10)
lap15 = laps.get_lap(15)

lap10.width = 5
lap15.width = 5

lap15_10 = lap10.resample(lap15, cs)

In [58]:
len(lap10.points), len(lap15.points), len(lap15_10.points)

(762, 764, 762)

In [59]:
px.line(pd.DataFrame({
    "dist": lap10.cum_distances,
    "lap10": [p.point.full_speed for p in lap10.points],
    "lap12": [p.point.full_speed for p in lap15_10.points],
}).set_index("dist"))

In [60]:
t10 = pd.Series([p.time for p in lap10.points])
t11 = pd.Series([p.time for p in lap15_10.points])

px.line(x=lap10.cum_distances, y=(t10 - t11).pipe(lambda s: s - s.iloc[0]))

In [62]:
data = pd.DataFrame(
    dict(
        x=np.array(cs.local(p.point).x for p in lap10.points),
        y=np.array(cs.local(p.point).y for p in lap10.points),
        x2=np.array(cs.local(p.point).x for p in lap15_10.points),
        y2=np.array(cs.local(p.point).y for p in lap15_10.points),
        cum_dist=lap10.cum_distances,
        lap10_time=np.array([p.time - lap10.points[0].time for p in lap10.points]),
        lap15_time=np.array([p.time - lap15_10.points[0].time for p in lap15_10.points]),
        lap10_speed=np.array([p.point.full_speed for p in lap10.points]),
        lap15_speed=np.array([p.point.full_speed for p in lap15_10.points]),
    )
).assign(
    delta=lambda d: d["lap10_time"]
    - d["lap15_time"]
    - d["lap10_time"].min()
    + d["lap15_time"].min(),
    lap10_time=lambda d: d["lap10_time"],
    lap15_time=lambda d: d["lap15_time"],
)

In [63]:
px.line(data.set_index("cum_dist"), y="delta", title="Lap 10.time - Lap 15.time")

In [64]:
fig = px.scatter(
    data.assign(ddelta=lambda d: d["delta"].diff().rolling(20).mean().shift(-10)),
    x="x",
    y="y",
    color="ddelta",
    hover_data=["cum_dist", "lap10_speed", "lap15_speed"],
    title="(smoothed) Derivative of delta in space. Positive = lap1 is losing time",
).update_layout(height=500, margin=dict(l=0, r=0, t=30, b=0))
for trace in (
    px.scatter(
        data.assign(ddelta=lambda d: -d["delta"].diff().rolling(20).mean().shift(-10)),
        x="x2",
        y="y2",
        color="ddelta",
        hover_data=["cum_dist", "delta", "lap10_speed", "lap15_speed"],
        title="(smoothed) Derivative of delta in space. Positive = lap1 is losing time",
    )
    .update_layout(height=500, margin=dict(l=0, r=0, t=30, b=0))
    .data
):
    fig.add_trace(trace)
fig.update_layout(height=600)

In [44]:
df = pd.DataFrame({
    "lat1": [p.point.lat for p in lap10.points], "lon1": [p.point.lon for p in lap10.points], "dist": [p for p in lap10.cum_distances]
})
px.scatter(df, x="lon1", y="lat1", color="dist", title="Lap 10")

In [12]:
px.histogram(good_sectors["S1"], nbins=30, title="Sector 1 times distribution")

In [13]:
px.histogram(good_sectors["S2"], nbins=14, title="Sector 2 times distribution")

In [14]:
px.histogram(good_sectors["S3"], nbins=30, title="Sector 3 times distribution")

In [15]:
raw_laptimes = """01 1:27.798 [18]
02 1:29.447 [17]
03 1:30.355 [17]
04 1:33.718 [17]
05 1:32.349 [16]
06 1:14.794 [16]
07 1:21.772 [16]
08 1:16.177 [16]
09 1:17.225 [15]
10 1:12.886 [15]
11 1:12.401 [15]
12 1:16.090 [14]
13 1:23.844 [14]
14 1:15.042 [15]
15 1:12.077 [15]
16 1:13.518 [15]
17 1:13.378 [14]
18 1:17.909 [15]
19 1:13.696 [14]
20 1:17.433 [15]
21 1:24.206 [15]
22 1:13.007 [15]
23 1:14.224 [16]
24 1:10.666 [16]
25 1:10.995 [15]
26 1:12.946 [15]
27 1:10.541 [15]
28 1:09.988 [14]
29 1:12.646 [14]
30 1:10.985 [14]
31 1:16.647 [14]
"""

official_laptimes = pd.DataFrame(
    [
        {
            "lap": int(line.split(" ")[0]),
            "lap_time": pd.to_timedelta("0:" + line.split(" ")[1]).total_seconds(),
            "position": int(re.search(r"\[(\d+)\]", line).group(1)),
        }
        for line in raw_laptimes.strip().split("\n")
    ]
)
comparison = official_laptimes.assign(
    guessed_laptime=laps_times.iloc[:-1]
    .iloc[-(len(official_laptimes)) :]["lap_time"]
    .values
)

In [16]:
comparison.assign(diff_seconds=comparison["lap_time"] - comparison["guessed_laptime"])[
    ["lap", "position", "lap_time", "guessed_laptime", "diff_seconds"]
]

    lap  position  lap_time  guessed_laptime  diff_seconds
0     1        18    87.798        87.575387      0.222613
1     2        17    89.447        89.867382     -0.420382
2     3        17    90.355        89.997406      0.357594
3     4        17    93.718        94.006442     -0.288442
4     5        16    92.349        92.006400      0.342600
5     6        16    74.794        74.906053     -0.112053
6     7        16    81.772        81.634098      0.137902
7     8        16    76.177        76.361253     -0.184253
8     9        15    77.225        76.983396      0.241604
9    10        15    72.886        72.819496      0.066504
10   11        15    72.401        72.506022     -0.105022
11   12        14    76.090        76.126776     -0.036776
12   13        14    83.844        83.782924      0.061076
13   14        15    75.042        75.090036     -0.048036
14   15        15    72.077        72.041584      0.035416
15   16        15    73.518        73.621476     -0.103476
16   17        14    73.378        73.262628      0.115372
17   18        15    77.909        77.971834     -0.062834
18   19        14    73.696        73.641327      0.054673
19   20        15    77.433        77.391599      0.041401
20   21        15    84.206        84.246799     -0.040799
21   22        15    73.007        73.121576     -0.114576
22   23        16    74.224        74.181782      0.042218
23   24        16    70.666        70.502277      0.163723
24   25        15    70.995        71.034427     -0.039427
25   26        15    72.946        72.965280     -0.019280
26   27        15    70.541        70.475203      0.065797
27   28        14    69.988        70.223159     -0.235159
28   29        14    72.646        72.466483      0.179517
29   30        14    70.985        70.953694      0.031306
30   31        14    76.647        76.847210     -0.200210

In [17]:
px.histogram(
    comparison["lap_time"] - comparison["guessed_laptime"],
    title="Difference between official and guessed lap times (seconds)",
)

In [18]:
laps_times.iloc[:-1].iloc[-(len(official_laptimes)) :]

    lap   lap_time         S1         S2         S3
5     5  87.575387  20.336977  31.814026  35.424385
6     6  89.867382  19.712480  33.589494  36.565409
7     7  89.997406  22.425588  30.669669  36.902150
8     8  94.006442  18.017138  33.650071  42.339234
9     9  92.006400  23.607023  34.743276  33.656100
10   10  74.906053  16.924699  26.750185  31.231169
11   11  81.634098  16.462314  28.954798  36.216986
12   12  76.361253  18.599654  26.575135  31.186463
13   13  76.983396  20.173796  26.366182  30.443418
14   14  72.819496  16.267761  26.261207  30.290529
15   15  72.506022  16.191267  25.940139  30.374616
16   16  76.126776  15.872928  27.849990  32.403859
17   17  83.782924  26.465303  26.758489  30.559132
18   18  75.090036  16.056109  26.335868  32.698059
19   19  72.041584  15.933709  26.042409  30.065466
20   20  73.621476  16.085170  26.103257  31.433049
21   21  73.262628  16.056021  25.974160  31.232447
22   22  77.971834  16.941234  26.608362  34.422239
23   23  73.641327  16.371805  26.109394  31.160128
24   24  77.391599  21.568277  25.829669  29.993653
25   25  84.246799  15.787987  27.893001  40.565810
26   26  73.121576  15.955786  25.301391  31.864399
27   27  74.181782  15.795908  26.453633  31.932241
28   28  70.502277  15.839360  24.750878  29.912039
29   29  71.034427  16.025561  24.887594  30.121273
30   30  72.965280  15.572035  25.365442  32.027803
31   31  70.475203  15.635415  25.072427  29.767361
32   32  70.223159  15.383012  25.049897  29.790251
33   33  72.466483  17.410506  25.768857  29.287120
34   34  70.953694  15.849335  24.844490  30.259868
35   35  76.847210  16.246936  25.540660  35.059614

In [19]:
lap1 = laps.get_lap(32)
lap2 = laps.get_lap(34)
lap1.points[0].time, lap2.points[0].time
locate_timestamp(lap1.points[0].time), locate_timestamp(lap1.points[-1].time)
locate_timestamp(lap1.points[0].time), locate_timestamp(lap2.points[0].time)
lap1.width = 10
lap21 = lap1.resample(lap2, cs)
start_time + pd.Timedelta(seconds=lap1.points[0].time)

Timestamp('2025-11-08 13:50:24.872534381')

In [20]:
lap1.count(), lap21.count()

(60, 60)

In [24]:
data = pd.DataFrame(
    dict(
        x=np.array(cs.local(p.point).x for p in lap1.points),
        y=np.array(cs.local(p.point).y for p in lap1.points),
        cum_dist=lap1.cum_distances,
        lap1_time=np.array([p.time for p in lap1.points]),
        lap2_time=np.array([p.time for p in lap21.points]),
        lap1_speed=np.array([p.point.full_speed for p in lap1.points]),
        lap2_speed=np.array([p.point.full_speed for p in lap21.points]),
    )
).assign(
    delta=lambda d: d["lap1_time"]
    - d["lap2_time"]
    - d["lap1_time"].min()
    + d["lap2_time"].min(),
    lap1_time=lambda d: d["lap1_time"],
    lap2_time=lambda d: d["lap2_time"],
)


lap1_time = data["lap1_time"].max() - data["lap1_time"].min()
lap2_time = data["lap2_time"].max() - data["lap2_time"].min()

px.line(
    data,
    x="cum_dist",
    y="delta",
    hover_data=["lap1_time", "lap2_time"],
    title=f"lap1_time ({lap1_time:.2f}) - lap2_time ({lap2_time:.2f})",
)

In [23]:
data

,x,y,cum_dist,lap1_time,lap2_time,lap1_speed,lap2_speed,delta
0,11.418309,-10.982559,0.000000,3535.872534,3678.562177,36.921012,33.995718,0.000000
1,9.883121,-12.950196,2.495709,3536.000000,3678.593799,38.429688,34.367034,0.095843
2,8.545892,-33.069262,22.660155,3537.000000,3679.689507,19.410156,24.341956,0.000136
3,15.702919,-51.817135,42.736620,3538.000000,3680.693091,19.750000,19.398879,-0.003449
4,42.67249,-83.304563,84.197150,3540.000000,3682.747168,40.269531,37.352013,-0.057525
5,57.790162,-89.650642,100.592781,3541.000000,3683.685318,16.910156,23.756296,0.004325
6,71.271996,-86.053978,114.547553,3542.000000,3684.681005,13.949219,14.737745,0.008637
7,84.392235,-82.634985,128.111824,3543.000000,3685.694226,13.050781,13.045213,-0.004584
8,95.308704,-88.720089,140.609734,3544.000000,3687.021052,12.230469,8.944201,-0.331410
9,103.814701,-97.499049,152.835194,3545.000000,3687.930337,10.429688,12.439266,-0.240695
10,115.041272,-108.282158,168.406654,3546.000000,3689.093829,14.132812,13.035306,-0.404186
11,127.524533,-107.602208,180.910009,3547.000000,3690.546886,11.597656,8.493917,-0.857243
12,131.054144,-102.197102,187.365498,3548.000000,3691.157669,5.468750,7.241341,-0.468027
13,125.779406,-93.904618,197.201537,3549.000000,3692.067763,9.523438,9.758216,-0.378121
14,118.662333,-86.057561,207.797233,3550.000000,3693.008891,10.136719,11.455389,-0.319249
15,91.681029,-68.165667,240.171770,3552.000000,3695.090314,32.089844,16.461525,-0.400672
16,74.491231,-46.601807,267.748739,3554.000000,3697.282547,28.441406,11.767779,-0.592905
17,79.048144,-37.748054,277.708369,3555.000000,3697.777644,8.589844,11.518297,-0.088001
18,90.176803,-40.570879,289.191195,3556.000000,3699.102943,11.128906,10.659243,-0.413301
19,110.494514,-57.596907,315.700338,3558.000000,3700.834568,26.031250,24.164521,-0.144926
20,149.885212,-101.676631,374.818914,3561.000000,3704.030872,58.218750,19.506122,-0.341229
21,151.194326,-118.758946,391.952478,3562.000000,3705.097322,16.460938,15.869747,-0.407679
22,143.31439,-130.601692,406.189844,3563.000000,3705.996306,14.019531,14.486154,-0.306663
23,131.439552,-135.101808,418.895041,3564.000000,3706.787865,12.480469,12.701617,-0.098223
24,118.106615,-128.644082,433.709542,3565.000000,3707.778993,14.628906,13.272471,-0.089350
25,107.488336,-116.294733,450.007158,3566.000000,3708.755963,14.710938,15.321429,-0.066320
26,94.694936,-107.078512,465.774523,3567.000000,3709.825458,14.699219,13.710218,-0.135815
27,82.31502,-109.60482,478.411155,3568.000000,3710.950476,11.453125,16.468994,-0.260833
28,81.19028,-121.253577,490.114085,3569.000000,3711.628222,10.597656,18.764329,0.061421
29,88.146671,-131.168865,502.226240,3570.000000,3712.937656,11.769531,10.500365,-0.248014
30,97.812133,-141.680505,516.506147,3571.000000,3714.014741,13.839844,13.713720,-0.325098
31,128.467246,-164.137931,554.507623,3573.000000,3715.910396,37.480469,42.202856,-0.220754
32,147.821141,-174.470865,576.450792,3574.000000,3716.985844,21.589844,58.365382,-0.296202
33,168.604046,-178.653141,597.654105,3575.000000,3717.955206,21.269531,22.836263,-0.265563
34,206.69105,-168.938742,636.968582,3577.000000,3719.983311,38.500000,18.042740,-0.293668
35,219.994914,-162.283126,651.849764,3578.000000,3721.029442,15.160156,14.418764,-0.339800
36,225.383861,-152.5725,662.955484,3579.000000,3721.782236,10.429688,11.342893,-0.092594
37,217.933702,-145.425812,673.281181,3580.000000,3722.738826,9.750000,8.660895,-0.049184
38,210.483483,-136.192302,685.152289,3581.000000,3723.799279,11.710938,11.252559,-0.109636
39,190.509308,-113.951251,715.056654,3583.000000,3725.810585,29.910156,28.591159,-0.120942
40,178.840563,-100.729963,732.700952,3584.000000,3726.811032,17.750000,20.385177,-0.121389
41,152.920434,-71.101564,772.099531,3586.000000,3728.742357,39.250000,21.026439,-0.052715
42,126.04769,-34.762083,817.311681,3588.000000,3730.727570,44.000000,22.671468,-0.037927
43,109.368754,-17.634805,841.219223,3589.000000,3731.729587,23.652344,23.074616,-0.039944
44,68.693962,-8.51096,882.906657,3591.000000,3733.806291,41.937500,18.941284,-0.116649
45,55.023007,-19.263332,900.309729,3592.000000,3734.747642,17.320312,18.614811,-0.057999
46,46.626487,-33.314542,916.689490,3593.000000,3735.703293,15.878906,16.646431,-0.013650
47,35.055979,-37.254013,928.938301,3594.000000,3736.934244,11.480469,9.895811,-0.244601
48,29.24199,-33.739511,935.743703,3595.000000,3738.100455,5.550781,7.331300,-0.410812
49,32.31822,-24.465818,945.522450,3596.000000,3739.168223,9.429688,8.059210,-0.478581
50,36.404552,-13.944649,956.809306,3597.000000,3740.133924,10.660156,12.110386,-0.444281
51,43.842617,-2.230618,970.685304,3598.000000,3741.149535,13.199219,19.227601,-0.459893
52,57.438996,2.624076,985.123773,3599.000000,3742.228561,13.453125,25.321869,-0.538918
53,69.141319,11.868026,1000.038020,3600.000000,3743.173920,14.296875,25.877637,-0.484278
54,65.7722,23.516082,1012.165180,3601.000000,3744.457161,11.019531,19.046919,-0.767519
55,57.272278,27.28953,1021.467193,3602.000000,3745.669436,8.113281,11.034041,-0.979794
56,45.403465,25.257868,1033.508637,3603.000000,3746.587099,11.417969,16.356382,-0.897456
57,32.977971,17.234118,1048.299629,3604.000000,3747.552062,14.378906,24.556680,-0.862419
58,20.730379,3.748832,1066.517651,3605.000000,3748.578562,17.730469,31.309203,-0.888920
59,14.709175,-15.589318,1086.774169,3606.095694,3749.515871,28.698104,36.081787,-0.730535

In [22]:
px.line(
    data,
    x="cum_dist",
    y=["lap1_speed", "lap2_speed"],
    title=f"lap1_time ({lap1_time:.2f}), lap2_time ({lap2_time:.2f})",
)

In [ ]:
locate_timestamp(800), locate_timestamp(1896)

In [95]:
px.scatter(
    data.assign(ddelta=lambda d: d["delta"].diff().rolling(1).mean()),
    x="x",
    y="y",
    color="ddelta",
    hover_data=["cum_dist", "lap1_speed", "lap2_speed"],
).update_layout(height=600)

In [51]:
(
    locate_timestamp(start_time + pd.Timedelta("591s")),
    locate_timestamp(start_time + pd.Timedelta("1947s")),
)

(('/Users/denys/Downloads/GX010108.MP4', Timedelta('0 days 00:10:13.900000')),
 ('/Users/denys/Downloads/GX030108.MP4', Timedelta('0 days 00:07:12.399000')))

In [ ]:
px.scatter(
    pd.DataFrame(
        dict(
            x=[cs.local(p.point).x for p in lap1.points],
            y=[cs.local(p.point).y for p in lap1.points],
            full_speed=[p.point.full_speed for p in lap1.points],
            cum_distance=lap1.cum_distances,
        )
    ),
    x="x",
    y="y",
    hover_data="cum_distance",
    color="delta",
).update_layout(height=600)

In [92]:
lap1.lap_time(), lap21.lap_time()

(48.32459112347226, 48.29960160144947)

In [23]:
fig = px.line(x=[cs.local(s).x for s in samples], y=[cs.local(s).y for s in samples])
fig.add_trace(
    px.line(
        x=[laps.sectors.start_line.first.x, laps.sectors.start_line.second.x],
        y=[laps.sectors.start_line.first.y, laps.sectors.start_line.second.y],
    ).data[0]
)
fig.add_trace(px.line(x=[s1.x, s2.x], y=[s1.y, s2.y]).data[0])

In [42]:
dir(laps.sectors)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'sector_lines',
 'start_line']

In [47]:
fig = px.line(x=[s.lat for s in samples], y=[s.lon for s in samples])

In [4]:
df = pd.DataFrame(
    [
        dict(
            lat=s.lat,
            lon=s.lon,
            alt=s.altitude,
            full_speed=s.full_speed,
            ground_speed=s.ground_speed,
            timestamp=pd.to_datetime(s.timestamp_ms, unit="ms"),
            begin=b,
            end=e,
        )
        for s, b, e in samples
    ]
)

In [130]:
df

,lat,lon,alt,full_speed,ground_speed,timestamp,begin,end
0,51.375703,-0.361656,22.978,0.07,0.056,2025-09-06 14:03:40.399,0.000,1.001
1,51.375705,-0.361657,23.221,0.06,0.073,2025-09-06 14:03:40.499,0.000,1.001
2,51.375706,-0.361658,23.402,0.08,0.070,2025-09-06 14:03:40.599,0.000,1.001
3,51.375707,-0.361659,23.567,0.09,0.050,2025-09-06 14:03:40.699,0.000,1.001
4,51.375709,-0.361660,23.766,0.06,0.054,2025-09-06 14:03:40.799,0.000,1.001
...,...,...,...,...,...,...,...,...
7682,51.376140,-0.361179,15.849,20.11,19.595,2025-09-06 14:16:28.599,767.767,768.768
7683,51.376129,-0.361199,15.887,19.60,19.230,2025-09-06 14:16:28.699,767.767,768.768
7684,51.376117,-0.361219,15.925,19.23,18.865,2025-09-06 14:16:28.799,767.767,768.768
7685,51.376105,-0.361236,15.963,18.87,18.022,2025-09-06 14:16:28.899,767.767,768.768
7686,51.376092,-0.361252,16.081,18.03,17.914,2025-09-06 14:16:29.000,767.767,768.768

In [129]:
px.line((df["timestamp"] - df["timestamp"].min()).dt.total_seconds() - df["begin"])